/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Main/About.vue')['default']
    Awards: typeof import('./src/components/Main/Awards.vue')['default']
    AwardsSection: typeof import('./src/components/SideMenu/AwardsSection.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Header_Component: typeof import('./src/components/Header_Component.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Location: typeof import('./src/components/Main/Location.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Main_Component: typeof import('./src/components/Main_Component.vue')['default']
    MainComponent: typeof import('./src/components/MainComponent.vue')['default']
    MainProfile: typeof import('./src/components/Main/MainProfile.vue')['default']
    PersonalInfo: typeof import('./src/components/Main/PersonalInfo.vue')['default']
    Posts: typeof import('./src/components/Main/Profile/Posts.vue')['default']
    Profile: typeof import('./src/components/SideMenu/Profile.vue')['default']
    ProfileBanner: typeof import('./src/components/ProfileBanner.vue')['default']
    ProfileBanner_Component: typeof import('./src/components/ProfileBanner_Component.vue')['default']
    ProfileBannerComponent: typeof import('./src/components/ProfileBannerComponent.vue')['default']
    Ratings: typeof import('./src/components/Main/Profile/Ratings.vue')['default']
    ReviewCard: typeof import('./src/components/Main/ReviewCard.vue')['default']
    Reviews: typeof import('./src/components/Main/Reviews.vue')['default']
    ReviewsCard: typeof import('./src/components/Main/ReviewsCard.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    SideMenu_Component: typeof import('./src/components/SideMenu_Component.vue')['default']
    SideMenu_Sub_AwardsSection: typeof import('./src/components/SideMenu_Sub_AwardsSection.vue')['default']
    SideMenu_Sub_Profile: typeof import('./src/components/SideMenu_Sub_Profile.vue')['default']
    SideMenu_Sub_Socials: typeof import('./src/components/SideMenu_Sub_Socials.vue')['default']
    SideMenu_SubAwardsSection: typeof import('./src/components/SideMenu_SubAwardsSection.vue')['default']
    SideMenuComponent: typeof import('./src/components/SideMenuComponent.vue')['default']
    SideMenuSubAwardsSection: typeof import('./src/components/SideMenu/SideMenuSubAwardsSection.vue')['default']
    SideMenuSubProfile: typeof import('./src/components/SideMenu/SideMenuSubProfile.vue')['default']
    SideMenuSubSocials: typeof import('./src/components/SideMenu/SideMenuSubSocials.vue')['default']
    Socials: typeof import('./src/components/SideMenu/Socials.vue')['default']
    SubAwardsSection: typeof import('./src/components/SideMenu/SubAwardsSection.vue')['default']
    SubProfile: typeof import('./src/components/SideMenu/SubProfile.vue')['default']
    SubSocials: typeof import('./src/components/SideMenu/SubSocials.vue')['default']
    Vehicles: typeof import('./src/components/Main/Vehicles.vue')['default']
    VehiclesCard: typeof import('./src/components/Main/VehiclesCard.vue')['default']
  }
}
